#!/bin/sh

# Cria um diretório para manter a raiz do projeto 'limpa'
COMPILE_DIR=out
if [ ! -d "$COMPILE_DIR" ]; then
  echo "-> Criando diretório para arquivos intermediários: $COMPILE_DIR"
  mkdir "$COMPILE_DIR"
fi

texfot --quiet pdflatex -interaction=nonstopmode -output-directory=out projeto 1> /tmp/projeto_latex.log

if [ $? -eq 0 ]; then
  echo "-> Primeira execução do pdflatex: SUCESSO"
else
  echo "-> Primeira execução do pdflatex: ERRO"
  cat /tmp/projeto_latex.log
  exit
fi

# http://code.snipcademy.com/tutorials/shell-scripting/looping/while-loops-shift-getopts

# parâmetros padrões
bibtex=true
view=false

#
while [ $# -gt 0 ]
do
  case $1 in
    -v | --view )
      view=true
      ;;
    -nb | --no-bibtex )
      bibtex=
      ;;
      # Opção não reconhecida
    -*) echo "-> $0: $1: opção não reconhecida" >&2
      ;;
    **) break
      ;;
  esac

  # shift for next option
  shift
done

if [ "$bibtex" = true ]; then
  echo "-> Executando o bibtex!"
  cp refs.bib out
  (cd out; bibtex -terse projeto)
    echo "-> Segunda execução do pdflatex!"
  texfot --quiet pdflatex -interaction=nonstopmode -output-directory=out projeto 1> /dev/null
    echo "-> Terceira execução do pdflatex!"
  texfot --quiet pdflatex -interaction=nonstopmode -output-directory=out projeto
else
  echo "-> O bibtex não foi executado!"
fi

if [ "$view" = true ]; then
  echo "-> Abrindo pdf com Evince!"
  evince ./out/projeto.pdf
else
  echo "-> Somente compilando!"
fi
