#!/bin/sh

rm -r out 2> /dev/null
mkdir out

texfot --quiet pdflatex -interaction=nonstopmode -output-directory=out projeto 1> /tmp/projeto_latex.log

if [ $? -eq 0 ]; then
  echo "pdflatex 1 -> SUCESSO"
else
  echo "pdflatex 1 -> ERRO"
  cat /tmp/projeto_latex.log
  exit
fi

cp refs.bib out
(cd out; bibtex -terse projeto)
texfot --quiet pdflatex -interaction=nonstopmode -output-directory=out projeto 1> /dev/null
texfot --quiet pdflatex -interaction=nonstopmode -output-directory=out projeto

if [ $1 = "-v" ] || [ $1 = "-view" ]; then
  echo "Compilando e abrindo com Evince!"
  evince ./out/projeto.pdf
else
  echo "Somente compilando!"
fi
