# -*- ispell-local-dictionary: "portugues"; -*-
* Cronograma

  #+BEGIN_EXPORT latex
  \begin{adjustbox}{center}
    \tiny
    \begin{tabular}{|p{4.1cm}|c|c|c|c|c|c|c|c|c|c|c|l|}
      \cline{1-12}
        \multicolumn{1}{|c|}{
          \multirow{2}{*}{
            \diagbox[width=4.4cm]{
              \textbf{Atividades}
            }{
              \textbf{Ano/Mês}
            }}}
        & \multicolumn{5}{c|}{\textbf{2017/1}}
        & \multicolumn{1}{c|}{\textbf{Férias}}
        & \multicolumn{5}{c|}{\textbf{2017/2}} \\
        \cline{2-12}
        & Mar. & Abr. & Maio & Jun. & Jul. & Ago. & Set. & Out. & Nov. & Dez. & Jan. \\
      \hline
        Definir e delimitar tema
        & X &  &  &  &  &  &  &  &  &  &  \\
      \hline
        Revisar literatura
        & X & X & X & X & X & X & & &  &  &  \\
      \hline
        Formular problema, questões norteadoras, e objetivos
        & & X & & &  &  &  &  &  &  &  \\
      \hline
        Redigir justificativa
        & & & X & & & & & & & & \\
      \hline
        Descrever métodos de pesquisa
        & & & & X & & & & & & & \\
      \hline
        Redigir fundamentação teórica
        & & & & X & X & & & & & & \\
      \hline
        Fazer cronograma e orçamento
        & & & X & & & & & & & & \\
      \hline
        Apresentar e entregar o projeto
        & & & & & X & & & & & & \\
      \hline
        Redigir introdução
        & & & & & & X & & & & & \\
      \hline
        Implementar estudos de caso
        & & & & & & X & X & X & & & \\
      \hline
        Análisar estudos de casos
        & & & & & & & X & X & X & & \\
      \hline
        Redigir desenvolvimento
        & & & & & & & X & X & X & X & \\
      \hline
        Redigir conclusão e resumo
        & & & & & & & & & X & X & \\
      \hline
        Revisar texto e referências
        & & & & & & & & & & X & X \\
      \hline
        Apresentar e entregar o TCC
        & & & & & & & & & & & X \\
      \hline
    \end{tabular}
  \end{adjustbox}
  #+END_EXPORT
