* Hipóteses
  O /Observer Pattern/ --- inerentemente orientado a objetos e /imperativo/ ---
  utiliza callbacks[fn:callbacks] como principal mecanismo de coordenação de
  eventos em GUIs. Porém a forma desconcertante com a qual /callbacks/ coordenam
  eventos faz com que o programa se torne difícil de compreender e, de modo
  geral, complexo e de manutenção laboriosa.

  PFR permite que aplicações interativas sejam programadas de forma
  /declarativa/ em um nível mais elevado[fn:abstracao] de abstração, com código
  fonte que expressa melhor a solução implementada. Como resultado, o programa
  se torna mais compreensível e, em geral, menos complexo e mais fácil de dar
  manutenção.


* Footnotes

[fn:abstracao] Em seu ensaio, \citeauthoronline{braithwaite2007} elucida:
  “\textelp{} quando o código se assemelha muito com a forma com a qual você
  explicaria sua solução pelo telefone, costuma-se dizer que ele é de ‘nível
  muito alto.’ (\citeyear{braithwaite2007}, tradução nossa)”.

[fn:callbacks] /Callbacks/ são funções registradas para tratar eventos ou computações
  assíncronas, e representão essêncialmente o mesmo conceito de /event
  handlers/, /event listeners/ ou /observers./
