# -*- ispell-local-dictionary: "portugues"; -*-
* Método de Pesquisa
  Apesar do paradigma de PFR ter sido apresentado há quase duas décadas com o
  artigo de \citeauthoronline{elliott1997} em \citeyear{elliott1997}, sua
  exploração e aplicação prática na indústria ainda é recente. Por esse motivo
  este trabalho tem um objetivo de cunho exploratório, que
  \citeauthoronline{gil2010metodos} descreve da seguinte forma:

  \begin{citacao}
  Pesquisas exploratórias são desenvolvidas com o objetivo de proporcionar visão
  geral, de tipo aproximativo, acerca de determinado fato. Este tipo de pesquisa
  é realizado especialmente quando o tema escolhido é pouco explorado e torna-se
  difícil sobre ele formular hipóteses precisas e operacionalizáveis
  (\citeyear{gil2010metodos}, p. 20). \end{citacao}

  Esse trabalho pretende estudar a usabilidade dos recursos oferecidos pelos
  /frameworks/ e/ou linguagens para a programação de interfaces gráficas. Como
  as propriedades a serem avaliadas não são quantificáveis, a abordagem a ser
  utilizada será /qualitativa/. Uma avaliação qualitativa não se preocupa com
  valores numéricos, mas procura aprofundar a compreensão do objeto de
  estudo~\cite[p.~31]{gerhardt2009metodos}. A análise qualitativa será feita no
  código fonte de estudos de caso implementados com as ferramentas a serem
  apresentadas --- o código utilizado para implementar as interfaces será
  avaliado, e não as interfaces em si. Para \citeauthoronline{santos2005manual},
  um estudo de caso:

  \begin{citacao}
  É o estudo que analisa com profundidade um ou poucos fatos, com vistas à
  obtenção de um grande conhecimento com riqueza de detalhes do objeto estudado.
  É usada nos estudos exploratórios e no início de pesquisas mas complexas. Tem
  aplicação em qualquer área do conhecimento (\citeyear{gil2010metodos}, p.
  172). \end{citacao}
